apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helse-repos
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 5
    timeoutSeconds: 3
  readiness:
    path: /isready
    initialDelay: 5
    timeoutSeconds: 3
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    inbound:
      rules:
        - application: tbd-website
    outboud:
        external:
          - host: https://api.github.com
  envFrom:
    - secret: helse-repos-github-api-token