name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
  
      - name: test and build
        run: ./gradlew test build
          
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.dockertag.outputs.docker_img }}
          context: /
  deployProd:
    name: Deploy to prod
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais.yml
          IMAGE: ${{ needs.set_version.outputs.image }}
