name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  set_version:
    name: set image name
    runs-on: ubuntu-latest
    steps:
      - name: create docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    outputs:
      image: docker.pkg.github.com/${{ github.repository }}/helse-repos:${{ env.TAG }}


  build:
    name: build docker image
    runs-on: ubuntu-latest
    needs: set_version
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
  
      - name: test and build
        run: ./gradlew test build
          
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: echo "::set-output name=docker_img::ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"

      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.dockertag.outputs.docker_img }}
          cache-from: type=registry,ref=${{ steps.dockertag.outputs.docker_img }}
          cache-to: type=inline
  deployProd:
    name: Deploy to prod
    needs: [ set_version, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais.yml
          IMAGE: ${{ needs.set_version.outputs.image }}
